# Generated by Django 4.1.7 on 2023-04-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='Address',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='fullname',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
