# Generated by Django 4.1.7 on 2023-04-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_admin_address_admin_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=40)),
            ],
        ),
    ]
