# Generated by Django 4.1.7 on 2023-05-03 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_report'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='traloiuser',
        ),
    ]
