# Generated by Django 4.1.7 on 2023-05-03 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '0007_wishlist'),
        ('Admin', '0005_rename_report_traloiuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='traloiuser',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webclient.user'),
        ),
    ]
