# Generated by Django 4.1.7 on 2023-04-12 01:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('fullname', models.CharField(max_length=40, null=True)),
                ('Address', models.CharField(max_length=40, null=True)),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Trường này chỉ dùng cho kiểu số.', regex='\\d*')])),
            ],
        ),
    ]
