# Generated by Django 4.1.7 on 2023-04-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webclient', '0004_cart_cart_product_many_many'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_product_many_many',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
